#!/usr/bin/env bash

export HIL_SERL_ROOT=/home/haoce/VLA_RL_Wyangchuan/hilserl/20260624/xarm_hil-serl-main
export PYTHONPATH=$HIL_SERL_ROOT:$HIL_SERL_ROOT/examples:$HIL_SERL_ROOT/serl_robot_infra:${PYTHONPATH:-}

echo "[HIL-SERL] root: $HIL_SERL_ROOT"
echo "[HIL-SERL] PYTHONPATH configured"


chmod +x setup_xarm_hilserl_env.sh

cd /home/haoce/VLA_RL_Wyangchuan/hilserl/20260624/xarm_hil-serl-main
conda activate hilserl
source setup_xarm_hilserl_env.sh

cd /home/haoce/VLA_RL_Wyangchuan/hilserl/20260624/xarm_hil-serl-main
conda activate hilserl
source setup_xarm_hilserl_env.sh

bash serl_robot_infra/robot_servers/launch_right_server.sh


cd /home/haoce/VLA_RL_Wyangchuan/hilserl/20260624/xarm_hil-serl-main
conda activate hilserl
source setup_xarm_hilserl_env.sh


cd /home/haoce/VLA_RL_Wyangchuan/hilserl/20260624/xarm_hil-serl-main
python examples/record_success_fail.py

===========================================================
import easyhid

hid = easyhid.Enumeration()
devices = hid.find()
print("HID devices:", len(devices))

for d in devices:
    print(d)
